spring:
  application:
    name: investment-service

  datasource:
    url: jdbc:h2:mem:investmentdb
    driver-class-name: org.h2.Driver
    username: marcin
    password: marcin

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  mvc:
    problemdetails:
      enabled: true
server:
  port: 4000

internal:
  key: internal-service-key

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs